# Generated by Django 4.0.4 on 2023-04-22 14:38

from django.db import migrations, models
import phonebookapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phonebook',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('contact', models.CharField(max_length=80)),
                ('phonebook_id', models.IntegerField(default=phonebookapp.models.phonebook.number)),
            ],
            options={
                'db_table': 'mstphonebook',
                'managed': False,
            },
        ),
    ]
